VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = no
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
VIALRGB_ENABLE = yes

CONSOLE_ENABLE = yes
RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = ws2812
